config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :posts, only: [:new, :create] do
    resources :comments
  end
  resources :users, only: [:show, :edit, :update]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_one_attached :image
  validate :image_presence

  def image_presence
    errors.add(:image, "can't be blank") unless image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :avatar
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

      if @comment.save
        flash[:success] = "Welll done for commenting!"
        redirect_to root_path
      else
        flash[:alert] = "Check the comment form, something went horribly wrong."
        render root_path
      end
    end

    def destroy
      @comment = @post.comments.find(params[:id])

      @comment.destroy
      flash[:success] = "Comment deleted :("
      redirect_to root_path
    end


private

  def comment_params
    params.require(:comment).permit(:content)
  end

  def set_post
    @post = Post.find(params[:post_id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_user
      @posts = Post.order(created_at: :desc).page(params[:page]).per(5)
    else
      redirect_to new_user_session_path
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :current_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def show

  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)

    redirect_to root_path
  end

  def edit

  end

  def update

    @post.update(post_params)

    redirect_to post_path(@post)
  end

  def destroy

    @post.destroy

    reditect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:description, :image, :user_id)
  end

  def current_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update]
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(created_at: :desc)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    current_user.update(user_params)
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:username, :name, :website,
                               :bio, :email, :phone, :gender, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="homepage">
  <div class='form-upload'>
    <%= form_for Post.new do |f| %>
      <div class="form-group">
        <%= f.text_field :description %>
      </div>
      <div class="form-group">
        <%= f.file_field :image %>
      </div>
      <div class="form-group">
        <%= f.text_field :user_id, value: current_user.id, class: 'd-none' %>
      </div>
      <br>
      <div class="text-center">
        <%= f.submit 'Create Post', class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>

  <div class="posts">
    <% @posts.each do |post| %>

      <section class="post">
        <div class="user">
          <div class="avatar">
            <% if post.user.avatar.attached? %>
              <%= image_tag post.user.avatar %>
            <% end %>
          </div>
          <div class="username">
            <%= post.user.username %>
          </div>
        </div>
        <%= image_tag post.image, class: 'main-image' %>
        <div class="description">
          <%= post.description %>

          <% if post.comments %>
            <% post.comments.each do |comment| %>
              <div class="comment">
                <div class="user-name">
                  <%= comment.user.username %>
                </div>
                <div class="comment-content">
                  <%= comment.content %>
                </div>
                <% if comment.user == current_user %>
                  <%= link_to 'Delete', post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" } %>
                <% end %>
              </div>
            <% end %>
          <% end %>

          <%= form_for [post, post.comments.new] do |f| %>
            <%= f.text_field :content, placeholder: 'Add a comment...' %>
          <% end %>
        </div>
      </section>

    <% end %>

    <%= paginate @posts %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instagram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--Navigation Bar-->
    <nav class="navbar navbar-light bg-light d-flex">
      <div class="container">
        <div class="logo">
          <a class="navbar-brand" href="<%= root_path %>">
            <%= fa_stacked_icon "camera inverse", base: "circle"%>
            Ri-stagram
          </a>
        </div>
        <div class="m-auto">
          <form class="form-inline search-form">
            <input class="form-control mr-sm-2" type="search" placeholder="@search" aria-label="Search">
          </form>
        </div>
        <div class="user-section">
          <a><i class="fa fa-compass"></i></a>
          <a><i class="fa fa-heart"></i></a>
            <% if user_signed_in? %>
              <a href="<%= user_path(current_user)%>">
                <i class="fa fa-user"></i>
              </a>
            <% else %>
              <a href="<%= new_user_session_path%>">
                <i class="fa fa-sign-in"></i>
              </a>
            <% end %>
        </div>
      </div>
    </nav>

    <!--Main content-->
    <main class="container" style="min-height: 500px;">
      <%= yield %>
    </main>
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

    <!--Footer-->
    <footer class="container footer">
      <nav class="navbar d-flex">
        <ul>
          <li>ABOUT US</li>
          <li>PROFILES</li>
          <li>HASHTAGS</li>
          <li>LANGUAGE</li>
        </ul>
        <p> © 2019 RI-STAGRAM </p>
      </nav>
    </footer>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<h3>Update Post Details</h3>
<%= form_with model: @post do |form| %>
  <%= form.text_field :description, placeholder: "Enter your description..." %>
  <%= form.text_field :image, placeholder: "image" %>

  <%= form.submit %>
<% end %>

app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.description, post_path(post) %></li>
  <% end %>
</ul>

<table>
  <% @posts.each do |post| %>
    <tr>
      <td><%= link_to post.description, post_path(post) %></td>
      <td><%= button_to 'Edit', edit_post_path(post), method: 'get'%></td>
      <td><%= button_to 'Remove', post_path(post), method: 'delete', data: { confirm: 'Are you sure?' } %></td>
  <% end %>
</table>
<%= link_to "Add a New Post", new_post_path %>

app/views/posts/new.html.erb
<h3>Create a Post</h3>
<%= form_with model: @post do |form| %>
  <%= form.text_field :description, placeholder: "Enter your description..." %>
  <%= form.text_field :image, placeholder: "image" %>

  <%= form.submit %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.description %><\h1>
<%= @post.image %><


<%= link_to 'Remove', @dog, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/users/edit.html.erb
<div class="user-edit-page">
  <div class="actions">
    <div class="nav flex-column nav-pills" role="tablist" aria-orientation="vertical">
      <a class="nav-link active" data-toggle="pill" href="#v-pills-home" role="tab" aria-selected="true">Edit Profile</a>
      <a class="nav-link" data-toggle="pill">Change Password</a>
      <a class="nav-link" data-toggle="pill">Authorized Applications</a>
      <a class="nav-link" data-toggle="pill">Email and SMS</a>
      <a class="nav-link" data-toggle="pill">Manage Contacts</a>
      <a class="nav-link" data-toggle="pill">Privacy and Security</a>
      <%= link_to 'Log Out', destroy_user_session_path, method: :delete, class: "nav-link" %>
    </div>
  </div>
  <div class="details tab-content">
    <div class="tab-pane fade show active" id="v-pills-home" role="tabpanel" aria-labelledby="v-pills-home-tab">
      <%= form_with model: current_user, local: true, html: {class: "form-horizontal form-edit-user"} do |f| %>
        <div class="form-group row">
          <div class="col-sm-3 col-form-label">
            <% if current_user.avatar.attached? %>
              <%= image_tag current_user.avatar, class: 'avatar' %>
            <%end %>
          </div>
          <div class="col-sm-9">
            <p class="username"><%=current_user.username %></p>
            <a class="change-photo" href="">Change Profile Photo</a>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :avatar, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.file_field :avatar, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :name, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :username, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :username, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :website, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :website, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :bio, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_area :bio, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :email, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :phone, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :gender, class: 'col-sm-3 col-form-label' %>
          <div class="col-sm-9">
            <%= f.text_field :gender, class: 'form-control' %>
          </div>
        </div>
        <div class="form-group row">
          <div class="col-sm-3">
          </div>
          <div class="col-sm-9">
            <%= f.submit "Submit", class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile">
  <div class="profile row">
    <div class="col-md-4 avatar">
      <div class="wrapper">
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar %>
        <%end %>
      </div>
    </div>
    <div class="col-md-8 basic-info">
      <div class="user-wrapper">
        <h2 class="username"><%= current_user.username %></h2>
        <a class="edit-profile" href="<%= edit_user_path(current_user) %>">
          <button>Edit Profile</button>
        </a>
      </div>
      <ul class="posts">
        <li><span><%= @posts.count %></span> posts</li>
        <li><span>195</span> followers</li>
        <li><span>345</span> following</li>
      </ul>
      <h2 class="name"><%=current_user.name %></h2>
      <%=link_to current_user.website, current_user.website, class: 'website' %>
    </div>
  </div>

  <div class="user-tabs">
    <a class="tab active" href="">
      <i class="fa fa-th"></i>
      POSTS
    </a>
    <a class="tab" href="">
      <i class="fa fa-tv"></i>
      IGTV
    </a>
    <a class="tab" href="">
      <i class="fa fa-bookmark"></i>
      SAVED
    </a>
    <a class="tab" href="">
      <i class="fa fa-tag"></i>
      TAGGED
    </a>
  </div>

  <div class="user-images">
    <% @posts.each do |post|%>
      <div class="wrapper">
        <%=image_tag post.image %>
      </div>
    <% end %>
  </div>
</div>